name: Deploy website to LH.pl

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy to LH via FTP
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        # action expects 'server-dir' (not 'remote-dir')
        server-dir: ${{ secrets.FTP_REMOTE_DIR }}
        protocol: ftp
        log-level: standard
        exclude: |
          .git*
          .github
          v1
          CNAME
          *.yml
          *.yaml
          *.md
          .gitignore
          README.md
