name: Deploy website to LH.pl

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy to LH via FTP
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Copy files via SCP
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 40022
        source: "./"
        target: ${{ secrets.FTP_REMOTE_DIR }}
